# Generated by Django 2.1.2 on 2018-10-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='noimage.png', upload_to=''),
            preserve_default=False,
        ),
    ]
